export default {
  READ_BY_ID: 'READ_BY_ID',
  READ_ALL: 'READ_ALL',
  NOTICE_START: 'NOTICE_START',
  NOTICE_FINISH: 'NOTICE_FINISH',
  RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
  START_LOGIN: 'START_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  CHANGE_AVATAR: 'CHANGE_AVATAR',
}